### PR TITLE
Frontend fix

### LINKED ISSUE #20: Frontend fixes
- [ ] Move stylings from gohtml to css
- [ ] Fix header being the wrong size
- [ ] Make frontpage usable on mobile

### PR DESCRIPTION
**Pull request by kmickols**
Closes #20

### CODE REVIEW

File: internal/web/report.go [hunk 1]
```diff
@@ -57,8 +57,8 @@ func getYearsSince2017() []string {
 
 func reportPage(w http.ResponseWriter, r *http.Request, databases Databases, perms []string, loggedIn bool) error {
 
-	currentYear := strconv.Itoa(time.Now().Year())
-	// currentYear := "2024"
+	//currentYear := strconv.Itoa(time.Now().Year())
+	currentYear := "2024"
```
Comment (DouglasFischer) [inline internal/web/report.go:61]: Nej

File: internal/web/report.go [hunk 2]
```diff
@@ -193,12 +193,12 @@ func findOrAddSecondaryCostCentre(secCostCentres *[]ReportSecondaryCostCentreLin
 func StructureReportLines(cashflowLines []CashflowLine, simpleBudgetLines []SimpleBudgetLine, selectedYear string) ([]ReportCostCentreLine, error) {
 	var costCentres []ReportCostCentreLine
 
-	currentYear := strconv.Itoa(time.Now().Year())
-	// currentYear := "2024"
+	//currentYear := strconv.Itoa(time.Now().Year())
+	currentYear := "2024"
```
Comment (DouglasFischer) [inline internal/web/report.go:197]: Nej

**Review by DouglasFischer — CHANGES_REQUESTED** [review]
Swap 2024 with current year

**Review by DouglasFischer — APPROVED** [review]
lgtm
